### PR TITLE
Fixed interaction timing, resolved farming bug.

### LINKED ISSUE #32: Fix interactables timings
Currently when interacting with a farm, there is a 1 second interaction timer.
Also when the player interacts with stone with its bare hands it mines the same speed as with a pickaxe.

### PR DESCRIPTION
**Pull request by goudcode**
closes #32

### CODE REVIEW

File: Assets/Interactables/Resources/Interactable.cs [hunk 1]
```diff
@@ -2,6 +2,12 @@
 
 public abstract class Interactable : MonoBehaviour, ITooltip
 {
+    public abstract float? InteractionTime { get; }
+    
     public abstract void Interact(Player player);
+
+    public virtual void InteractSingle(Player player)
+    { }
+
```
Comment (WouterHeslinga) [inline Assets/Interactables/Resources/Interactable.cs:11]:
```suggestion
```
